# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.cache/wt [current_project]
set_property parent.project_path /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library my_library {
  /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.srcs/sources_1/new/And_gate.vhd
  /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.srcs/sources_1/new/Or_gate.vhd
  /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.srcs/sources_1/new/my_package.vhd
}
read_vhdl -library xil_defaultlib /home/lauro199471/Documents/VHDL-Tutorial/Example_Project_1/Example_Project_1.srcs/sources_1/new/Top_Design.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Design -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Design.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Design_utilization_synth.rpt -pb Top_Design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
